# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_generate_hit_and_run_samples <- function(num_samples, burn_in, init_y, A, b) {
    .Call('_prototest_rcpp_generate_hit_and_run_samples', PACKAGE = 'prototest', num_samples, burn_in, init_y, A, b)
}

rcpp_maximise_approx_likelihood <- function(y_mat, V, groups, mu, sigma) {
    .Call('_prototest_rcpp_maximise_approx_likelihood', PACKAGE = 'prototest', y_mat, V, groups, mu, sigma)
}

rcpp_maximise_likelihood <- function(init_theta, y, V, groups, mu, sigma, sm_inv) {
    .Call('_prototest_rcpp_maximise_likelihood', PACKAGE = 'prototest', init_theta, y, V, groups, mu, sigma, sm_inv)
}

rcpp_compute_lr_stat <- function(U, y, mu, sigma, exact, verbose, tol, maxit) {
    .Call('_prototest_rcpp_compute_lr_stat', PACKAGE = 'prototest', U, y, mu, sigma, exact, verbose, tol, maxit)
}

